### ISSUE TITLE
Aragon-Italy Formation Bug

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#1]
If Provence has been exiled to Italy (i.e. annexed Eutria and then had their shit in France annexed by Occitania), they won't be annexed like the rest of the minors and will have to be manually attacked.

**Comment by TheDeNuke** [comment]
That seems like a exceptionally rare and interesting chain of events to run into that particular circumstance. To be fair that's because the AI is rigged to never actually start the war in Italy for some strange reason.

I'll change it so AI Only PRV gets cores on Italy if they successfully take Tuscany. That should prevent the oversight by virtue of them actually being able to take Italy and not effectively break in the circumstances that they take Tuscany. I'll also set a "PRV_in_Italy" flag on the same event to allow Aragon-Italy to annex them.
