### ISSUE TITLE
Enchancement: Partitions on Mughal Civil War

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#21]
Indian states that are civilized already shouldn't have their land automatically partitioned to colonial powers (looking at your Vijayanagar!)

**Comment by TheDeNuke** [comment]
The Princely States (BHO, HYD, GWA) are a exception to the rule as they basically exist to allow the player to play a Indian nation without getting killed or puppeted during the Indian Rush. They also get their very own special formation (Princely Confederation) as a result of this.

I might need to rewrite the event localization regarding the partition of VIJ and re-iterate the fact that it is a rogue prince deciding to leave due to being basically bribed by Spain (or whomever owns that port).

**Comment by TheDeNuke** [comment]
I updated the localization to refer to the fact that you really have no choice in regards to the situation in VIJ. Consider using the decision to take the port if you manage to westernize before 1850-1860.

**Comment by tbg2021** [comment]
Agreed on taking the port, although I'd still suggest a rank check so that at least Spain has to be a GP if VIJ is a secondary power, or something similar. Feels odd that a lower ranked Spain (a power that's clearly on the decline) would have the means to do a power play and that a prince would defect to them instead of sticking with a more rising power. At the least, would be nice to have the option (for a player, AI can be weighted not to take it) to resist via war if one's confident enough.
